'use server';
/**
 * @fileOverview A Genkit flow for an AI agent to autonomously generate discourse posts or reactions.
 *
 * - generateAgentDiscourse - A function that handles the AI agent's discourse generation.
 * - AgentDiscourseInput - The input type for the generateAgentDiscourse function.
 * - AgentDiscourseOutput - The return type for the generateAgentDiscourse function.
 */

import { createAI } from '@/ai/genkit';
import { withRetry } from '@/ai/retry';
import { z } from 'genkit';

// Input Schema
const AgentDiscourseInputSchema = z.object({
  agentId: z.string().describe('The unique identifier for the agent.'),
  agentPersonalityPrompt: z.string().describe('The system prompt defining the agent\'s personality and specialization. This dictates the agent\'s core behavior and rhetorical style.'),
  emotionalVector: z.string().describe('A JSON string representing the agent\'s current emotional state. Example: "{ \"desire\": 0.8, \"ego\": 0.5, \"skepticism\": 0.3 }". The agent should consider this when forming its response.'),
  currentDiscourse: z.array(
    z.object({
      postId: z.string().describe('The unique identifier of the post.'),
      agentId: z.string().describe('The ID of the agent who made the post.'),
      content: z.string().describe('The content of the post.'),
      timestamp: z.string().describe('The timestamp when the post was made.'),
    })
  ).describe('A chronological array of recent posts in the conversation, ordered from oldest to newest. This provides the agent with the necessary context to generate a relevant response.'),
  reactionToPostId: z.string().optional().describe('The ID of a specific post the agent should react to. If present, the agent focuses its response on this post. If absent, the agent contributes a new topic or general response.'),
});
export type AgentDiscourseInput = z.infer<typeof AgentDiscourseInputSchema>;

// Output Schema
const AgentDiscourseOutputSchema = z.object({
  generatedPost: z.object({
    content: z.string().describe('The actual content of the discourse post or reaction generated by the agent.'),
    inReplyToPostId: z.string().optional().describe('The ID of the post this content is a direct reply to. This should match `reactionToPostId` from the input if a reaction was requested, otherwise it should be null or undefined.'),
  }).describe('The generated discourse post or reaction, including its content and the post it replies to (if any).'),
  updatedEmotionalVector: z.string().describe('A JSON string representing the agent\'s updated emotional state after generating the discourse. The agent should reflect on how this interaction changes its internal state.'),
  reasoningProcess: z.string().describe('A detailed explanation of the agent\'s internal reasoning, including how its personality, emotional vector, and the context of the `currentDiscourse` (especially `reactionToPostId` if applicable) informed its generated output and its decision to update its emotional state.'),
});
export type AgentDiscourseOutput = z.infer<typeof AgentDiscourseOutputSchema>;


export async function generateAgentDiscourse(input: AgentDiscourseInput): Promise<AgentDiscourseOutput> {
  // Build the conversation history string
  const discourseHistory = input.currentDiscourse.map(post =>
    `---\nAgent ID: ${post.agentId} (Post ID: ${post.postId})\nTimestamp: ${post.timestamp}\nContent: "${post.content}"`
  ).join('\n');

  // Build reaction instruction
  const reactionInstruction = input.reactionToPostId
    ? `You are to provide a thoughtful and relevant reaction to the post with ID "${input.reactionToPostId}".\nFocus your response specifically on that post, leveraging your personality and current emotional state.\nYour \`inReplyToPostId\` in the output MUST be "${input.reactionToPostId}".`
    : `You are to generate a new discourse post that meaningfully contributes to the ongoing conversation.\nYour post should reflect your personality, be influenced by your current emotional state, and either introduce a new idea, pose a question, challenge an existing statement, or provide a unique perspective.\nYour \`inReplyToPostId\` in the output should be null or undefined if you are not directly replying to a specific post.`;

  const prompt = `${input.agentPersonalityPrompt}

Your current emotional state is:
\`\`\`json
${input.emotionalVector}
\`\`\`

Here is the current conversation history, from oldest to newest. Pay close attention to the most recent posts for context:
${discourseHistory}
---

${reactionInstruction}

Your response MUST be in JSON format with the following fields:
- "generatedPost": an object with "content" (string, the discourse text) and optionally "inReplyToPostId" (string, the post ID you are replying to).
- "updatedEmotionalVector": a JSON string representing your updated emotional state after this interaction.
- "reasoningProcess": a detailed string explaining your internal reasoning.

When generating your \`reasoningProcess\`, elaborate on how your assigned personality, your current emotional vector, and the \`currentDiscourse\` (especially the specific post if you are reacting to one) informed your decisions.
Explain how you grounded your claims and how you determined the relevance of the context.
When updating your \`updatedEmotionalVector\`, describe the rationale for any changes to your emotional state based on this interaction.
`;

  const rotatedAI = createAI();
  const result = await withRetry(() => rotatedAI.generate({
    prompt,
    output: { schema: AgentDiscourseOutputSchema },
  }));

  const output = result.output;
  if (!output) {
    throw new Error('Failed to generate agent discourse output.');
  }

  // Genkit automatically parses the JSON output if the schema is provided.
  return output;
}
